oro_entity_config:
    # Scope of entity merge
    merge:
        # Attributes applicable on entity level
        entity:
            items:
                # Options for rendering entity as string in the UI.
                # If these options are empty __toString will be used (if it's available).
                #
                # Method of entity to cast object to string
                merge_cast_method: ~
                # Twig template to render object as string
                merge_template: ~
                # Enable merge for this entity
                merge_enable:
                    options:
                        is_bool: true

        # Attributes applicable on entity fields level
        field:
            items:
                # Label of field that should be displayed for this field in merge UI, value will be translated
                merge_label: ~
                # Enable merge for this field
                merge_enable:
                    options:
                        is_bool: true
                # Option for sorting field on UI
                merge_priority: ~
                # Mode of merge supports next values: default, readonly, hidden
                #   default  - field will be used during merged and user will be able to choose a value of this field from entities
                #   readonly - user will not be able to choose a value and value will be used from master entity, but user will see entities values for this field
                #   hidden - field is not used in merge, value will be used from master entity
                merge_mode: ~
                # Options for rendering field value in the UI
                #
                # Method will be used to cast value to string (applicable only for values that are objects)
                merge_cast_method: ~
                # Template can be used to render value of field
                merge_template: ~
                # Method for setting value to entity
                merge_setter: ~
                # Method for getting value to entity
                merge_getter: ~
                # Can be used if you want to be able to merge this field for entity on other side of relation,
                # For example there is a Call entity with field referenced to Account using ManyToOne unidirectional relation.
                # As Account doesn't have access to collection of calls the only possible place to configure calls merging
                # for account is this field in Call entity
                merge_relation_enable:
                    options:
                        is_bool: true
                # Same as merge_mode but used for relation entity
                merge_relation_mode: ~
                # Same as merge_label but used for relation entity
                merge_relation_label: ~
                # Same as merge_priority but used for relation entity
                merge_relation_priority: ~
