parameters:
    oro_entity_merge.extension.mass_action.type.merge.class: Oro\Bundle\EntityMergeBundle\DataGrid\Extension\MassAction\MergeMassAction
services:
    oro_entity_merge.extension.mass_action.type.merge:
        class: %oro_entity_merge.extension.mass_action.type.merge.class%
        scope: prototype
        tags:
            - { name:  oro_datagrid.extension.mass_action.type, type: merge }
