parameters:
    oro_entity_merge.mass_action.merge.class: Oro\Bundle\EntityMergeBundle\DataGrid\Extension\MassAction\MergeMassAction
    oro_entity_merge.mass_action.data_handler.class: Oro\Bundle\EntityMergeBundle\DataGrid\Extension\MassAction\MergeMassActionHandler
services:
    oro_entity_merge.mass_action.merge:
        class: %oro_entity_merge.mass_action.merge.class%
        scope: prototype
        tags:
            - { name:  oro_datagrid.extension.mass_action.type, type: merge }

    oro_entity_merge.mass_action.data_handler:
        class: %oro_entity_merge.mass_action.data_handler.class%
        arguments:
            - @oro_entity_merge.doctrine_helper

