config:
    map:
       '*':
          'oro/datagrid/merge-mass-action': 'oro/entity-merge/merge-mass-action'
    paths:
        'oro/entity-merge/merge-mass-action': 'bundles/oroentitymerge/js/datagrid/action/merge-mass-action.js'
        'oro/entity-merge/merge-view': 'bundles/oroentitymerge/js/merge-view.js'
