parameters:
    oro_entity_merge.metadata.factory.class: Oro\Bundle\EntityMergeBundle\Metadata\MetadataFactory

services:
    oro_entity_merge.metadata.factory:
        class: %oro_entity_merge.metadata.factory.class%
        arguments:
            - @oro_entity_config.provider.merge
            - @doctrine.orm.entity_manager
