parameters:
    oro_entity_merge.metadata.merge_factory.class: Oro\Bundle\EntityMergeBundle\Metadata\MetadataFactory

services:
    oro_entity_merge.metadata.merge_factory:
        class: %oro_entity_merge.metadata.merge_factory.class%
        arguments:
            - @oro_entity_config.config_manager
            - @doctrine.orm.entity_manager
