parameters:
    #Metadata
    oro_entity_merge.metadata.factory.class: Oro\Bundle\EntityMergeBundle\Metadata\MetadataFactory

    #Entity Data
    oro_entity_merge.data.entity_provider.class: Oro\Bundle\EntityMergeBundle\Data\EntityProvider
    oro_entity_merge.data.entity_data_factory.class: Oro\Bundle\EntityMergeBundle\Data\EntityDataFactory

    # Merger
    oro_entity_merge.merger.class: Oro\Bundle\EntityMergeBundle\Model\EntityMerger

    # Accessors
    oro_entity_merge.accessor.delegate.class: Oro\Bundle\EntityMergeBundle\Model\Accessor\DelegateAccessor
    oro_entity_merge.accessor.default.class: Oro\Bundle\EntityMergeBundle\Model\Accessor\DefaultAccessor
    oro_entity_merge.accessor.relation.class: Oro\Bundle\EntityMergeBundle\Model\Accessor\RelationAccessor

    # Strategies
    oro_entity_merge.strategy.delegate.class: Oro\Bundle\EntityMergeBundle\Model\Strategy\DelegateStrategy
    oro_entity_merge.strategy.replace.class: Oro\Bundle\EntityMergeBundle\Model\Strategy\ReplaceStrategy
    oro_entity_merge.strategy.merge.class: Oro\Bundle\EntityMergeBundle\Model\Strategy\MergeStategy
services:
    oro_entity_merge.data.entity_data_factory:
        class: %oro_entity_merge.data.entity_data_factory.class%
        arguments:
            - @oro_entity_merge.metadata.factory
            - @oro_entity_merge.data.entity_provider

    oro_entity_merge.data.entity_provider:
        class: %oro_entity_merge.data.entity_provider.class%
        arguments:
            - @doctrine.orm.entity_manager

    oro_entity_merge.metadata.factory:
        class: %oro_entity_merge.metadata.factory.class%
        arguments:
            - @oro_entity_config.provider.merge
            - @doctrine.orm.entity_manager

    # Merger
    oro_entity_merge.merger:
        class: %oro_entity_merge.merger.class%
        arguments:
            - @oro_entity_merge.strategy
            - @event_dispatcher

    # Accessors
    oro_entity_merge.accessor.delegate:
        class: %oro_entity_merge.accessor.delegate.class%

    oro_entity_merge.accessor:
        alias: oro_entity_merge.accessor.delegate

    oro_entity_merge.accessor.default:
        class: %oro_entity_merge.accessor.default.class%
        tags:
            - { name: oro_entity_merge.accessor }

    oro_entity_merge.accessor.relation:
        class: %oro_entity_merge.accessor.relation.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_entity_merge.accessor }

    # Strategies
    oro_entity_merge.strategy.delegate:
        class: %oro_entity_merge.strategy.delegate.class%

    oro_entity_merge.strategy:
        alias: oro_entity_merge.strategy.delegate

    oro_entity_merge.strategy.replace:
        class: %oro_entity_merge.strategy.replace.class%
        arguments:
            - @oro_entity_merge.accessor.delegate
        tags:
            - { name: oro_entity_merge.strategy }

    oro_entity_merge.strategy.merge:
        class: %oro_entity_merge.strategy.merge.class%
        arguments:
            - @oro_entity_merge.accessor.delegate
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_entity_merge.strategy }
