parameters:
    oro_entity_merge.metadata.factory.class: Oro\Bundle\EntityMergeBundle\Metadata\MetadataFactory
    oro_entity_merge.mass_action.data_handler.class: Oro\Bundle\EntityMergeBundle\DataGrid\Extension\MassAction\Actions\Merge\MergeMassActionHandler
    oro_entity_merge.mass_action.entity_data_provider.class: Oro\Bundle\EntityMergeBundle\DataGrid\Extension\MassAction\Actions\Merge\MergeEntitiesDataProvider
    oro_entity_merge.http_foundation.merge_data_request_factory.class: Oro\Bundle\EntityMergeBundle\HttpFoundation\MergeDataRequestFactory

    # Merger
    oro_entity_merge.merger.class: Oro\Bundle\EntityMergeBundle\Model\EntityMerger

    # Accessors
    oro_entity_merge.accessor.delegate.class: Oro\Bundle\EntityMergeBundle\Model\Accessor\DelegateAccessor
    oro_entity_merge.accessor.default.class: Oro\Bundle\EntityMergeBundle\Model\Accessor\DefaultAccessor

    # Strategies
    oro_entity_merge.strategy.delegate.class: Oro\Bundle\EntityMergeBundle\Model\Strategy\DelegateStrategy
services:
    oro_entity_merge.mass_action.data_handler:
        class: %oro_entity_merge.mass_action.data_handler.class%
        calls:
            - [setMergeDataProvider, [@oro_entity_merge.mass_action.entity_data_provider]]
    oro_entity_merge.mass_action.entity_data_provider:
        class: %oro_entity_merge.mass_action.entity_data_provider.class%
        calls:
            - [setDoctrineRegistry, [@doctrine]]
    oro_entity_merge.http_foundation.merge_data_request_factory:
        class: %oro_entity_merge.http_foundation.merge_data_request_factory.class%
        score: request
        arguments:
            - @oro_datagrid.mass_action.parameters_parser
            - @oro_datagrid.mass_action.dispatcher
            - @oro_entity_merge.metadata.factory
        calls:
            - [setRequest, [@?request=]]

    oro_entity_merge.metadata.factory:
        class: %oro_entity_merge.metadata.factory.class%
        arguments:
            - @oro_entity_config.provider.merge
            - @doctrine.orm.entity_manager

    # Merger
    oro_entity_merge.merger:
        class: %oro_entity_merge.merger.class%
        arguments:
            - @oro_entity_merge.strategy
            - @event_dispatcher

    # Accessors
    oro_entity_merge.accessor.delegate:
        class: %oro_entity_merge.accessor.delegate.class%

    oro_entity_merge.accessor:
        alias: oro_entity_merge.accessor.delegate

    oro_entity_merge.accessor.default:
        class: %oro_entity_merge.accessor.default.class%
        tags:
            - { name: oro_entity_merge.accessor }

    # Strategies
    oro_entity_merge.strategy.delegate:
        class: %oro_entity_merge.strategy.delegate.class%

    oro_entity_merge.strategy:
        alias: oro_entity_merge.strategy.delegate

