parameters:
    oro_entity_merge.twig.extension.class: Oro\Bundle\EntityMergeBundle\Twig\MergeExtension

services:
    oro_entity_merge.twig.extension:
        class: %oro_entity_merge.twig.extension.class%
        arguments:
            - @oro_entity_merge.accessor
        tags:
            - { name: twig.extension }
