Oro\Bundle\EntityMergeBundle\Data\EntityData:
    properties:
        masterEntity:
            - NotBlank: ~
    constraints:
        - Oro\Bundle\EntityMergeBundle\Validator\Constraints\MaxEntities: ~
